### PR TITLE
Make middleware plural like the other folders

### PR DESCRIPTION
**Pull request by steffendsommer**
Opted in to make the middleware folder in plural to align with the other folders.

### CODE REVIEW

**Comment by vzsg** [comment]
I don't think middleware has a plural form like that, similarly to software and hardware.

**Comment by grundoon** [comment]
Pardon my amusement 😆, but this is sort of an oddity of English. `ware` is what's known as an "uncounted" – that is to say, it refers to any quantity (0 or 1 or >1) of a *type* of thing. Software, hardware, tableware, dinnerware, glassware, silverware...

`Wares` is indeed a valid plural form, but it is generally unnecessary and less often used because `ware` is already implied plural, and it usually refers to "an unspecified quantity of types of things" (e.g. Hello Mr. Market Stall Vendor, what wares are you selling today?). This is not really all that different from `die Ware` versus `die Waren`, but the `-wares` form sounds awkward to an (American) English speaker, sort of exactly like it is being translated from another language with different plural form rules.

(That said, I really don't care. It'll just give me a chuckle every time I read it. 🙂)

**Comment by mcdappdev** [comment]
Makes sense! Probably a good case study on why I shouldn't try to approve or deny grammar based changes right after I wake up 😆 @steffendsommer Are you ok keeping it how it was in light of this grammar knowledge? (Thanks @grundoon and @vzsg!)

**Comment by tanner0101** [comment]
Yeah this is a weird one. I use `Middlewares` some places in code where I needed a separate type name for a collection of middleware that didn't conflict with `Middleware`. But then other places like `MiddlewareConfig` don't use the `s`. 

My vote would be to just leave it as is, since I think both are correct and understandable. But I could go either way.

**Comment by tanner0101** [comment]
> what wares are you selling today

Lol. Sounds like something I would say when playing dnd.

**Comment by steffendsommer** [comment]
Yes, I'm definitely okay with leaving as it is. Thanks for the feedback everyone 👍

**Pull request closed without merging**
