### PR TITLE
 Translate to Chinese

### PR DESCRIPTION
**Pull request by mengxiangyue**
I translated the document into Chinese. Due to the limited level, there may be inaccurate translations in some places. I will continue to update the translation and try to keep in sync with the English version.
I use the ` current_version.md`  file to record the translated version.
Some places I do not know, so I retained the English, after I clear it will update it.
I am not goog at English.

如果你擅长中文，咱们可以用中文交流。

### CODE REVIEW

**Comment by tannernelson** [comment]
I think we should make a fork of this repo and translate that to Chinese. The links generated here keep pointing back to `https://vapor.github.io/documentation/` so it will always go back to the English version.

The fork could be `https://vapor.github.io/documentation-zh` and then couscous could properly generate links.

Here is the repository I've created: https://github.com/vapor/documentation-zh

Can you create a PR to this repo that is a copy of this repo but with all `*.md` documents translated to Chinese?

Do not bother translating any documents in the `.couscous` folder. Those are generated from the markdown files and will be regenerated when I publish the chinese docs.

Thanks!

**Comment by mengxiangyue** [comment]
@tannernelson I can't fork `https://vapor.github.io/documentation-zh` because the fork button is disable.

**Comment by tannernelson** [comment]
@mengxiangyue I've added you to the contributors team which has write access to the docs.

**Comment by mengxiangyue** [comment]
OK,I have already submitted。 I will continue to update the translation and try to keep in sync with the English version.

**Comment by tanner0101** [comment]
Sorry we haven't been able to merge this yet. We've been working on remastering the docs for Vapor 2. The folder structure is a lot different now and the docs for Vapor 2 have been rewritten. Because of the big changes, this PR needs to be updated quite a bit. I'm going to close it for now, but please feel free to re-open if/when it gets updated to the new structure. Thank you!

**Pull request closed without merging**
