### PR TITLE
Clarify custom command documentation

### PR DESCRIPTION
**Pull request by bjudson**
* Command class should be public
* ~~Give example of ConfigInitializable that will work with the command~~

### CODE REVIEW

**Comment by bjudson** [comment]
Looks like the ConfigInitializable has now been updated in master with code equivalent to what I added here. So the only relevant change now is making the command class public.

**Comment by vzsg** [comment]
Why should the Command be public though, if you follow the structure of the templates and add the command in the App module?

**Comment by bjudson** [comment]
@vzsg I found that if the command class is not public, when I try to build I get an unresolved identifier error for this line in `Run/main.swift`:
```
config.addConfigurable(command: MyCommand.init, name: "my-command")
```

**Comment by vzsg** [comment]
Yeah, that's exactly what I meant. You're not supposed to call `addConfigurable` in main.swift, or even edit that file, if you follow the current recommended practice.

**Comment by bjudson** [comment]
Hmm... in that case should this section be removed from the docs? https://github.com/vapor/documentation/blob/master/2.0/docs/vapor/commands.md#add-to-droplet

**Comment by vzsg** [comment]
Honestly? Yeah, it would be better if all the docs and templates were consistent on the patterns (even though the framework doesn't _require_ the user to follow them).

Paging @vapor/moderators

**Comment by bjudson** [comment]
Now that I know editing main.swift is an anti-pattern, I moved the addConfigurable call into the Config+Setup.swift file, and was able to make the command class private. I'd be happy to write this up for the docs if this is the recommended approach.

**Comment by tanner0101** [comment]
It's recommended to follow the templates and do `config.addConfigurable` within the app module. However I don't know if it's a good idea to reference template structure everywhere in the documentation as its likely to change. The documentation should also work for developers using just certain packages of Vapor or Vapor w/ their own template. 

Perhaps a page of documentation describing best practices / the state of the art in terms of templating would be better. That way if we change how the templates are laid out it doesn't affect the entire docs.

**Comment by tanner0101** [comment]
Track here: https://github.com/vapor/documentation/issues/193

**Comment by bjudson** [comment]
That makes sense to me. The reason I opened this PR is that the code in the Command example doesn't actually work as written. The command class is private, but it needs to be public if you're importing it to `main.swift`, as the example shows. Maybe it's not a big enough deal to fix right now, but it was frustrating for someone using Vapor to learn Swift.

**Comment by tanner0101** [comment]
The example was assuming you created the command in the same module as the `main.swift` file, in which case it would work.

**Pull request closed without merging**
