### PR TITLE
Fix tip section in fluent/query

### PR DESCRIPTION
**Pull request by albinekcom**

### CODE REVIEW

**Comment by tanner0101** [comment]
tabs should be 4 spaces here i think.

**Comment by albinekcom** [comment]
I have fixed (now it is like other notes in that particular document) but I have also noticed that in other documents there are 2 tabs here.

**Comment by tanner0101** [comment]
hmm, now it appears to be a tab character. the docs _should_ be indented using 4 spaces. although it's very likely that's been messed up in quite a few places haha.

**Comment by albinekcom** [comment]
OK, I have changed to `4 spaces`. It will be nice to format all documents to one standard in the next version.

**Pull request closed without merging**
