### PR TITLE
Adds link to HTTPResponseStatus struct property list.

### PR DESCRIPTION
**Pull request by EricWVGG**

### CODE REVIEW

**Comment by 0xTim** [comment]
@EricWVGG these don't come from the Swift Server working group - they come from Apple's NIO library https://github.com/apple/swift-nio/blob/master/Sources/NIOHTTP1/HTTPTypes.swift#L1190

**Comment by EricWVGG** [comment]
I was told on the Discord that Vapor was using this lib, apologies if I was misinformed.

Where is the true list of struct properties?

**Comment by 0xTim** [comment]
Well all the base ones should be in that file - there may be some extensions lying around elsewhere. But that file contains the actual `enum` model (which you can find by clicking through to it in Xcode)

**Comment by 0xTim** [comment]
This is probably the link you want https://apple.github.io/swift-nio/docs/current/NIOHTTP1/Enums/HTTPResponseStatus.html

**Comment by grundoon** [comment]
Yeah, sorry about that @EricWVGG – thought you were just looking for the values, etc., didn't look closely at the URL, just the info it was providing.

**Comment by penny-coin** [comment]
Hey @EricWVGG, you just merged a pull request, have a coin! 

You now have 2 coins.

**Pull request merged**
