### PR TITLE
Add fluent-dynamodb

### PR DESCRIPTION
**Pull request by Yasumoto**

### CODE REVIEW

**Comment by Yasumoto** [comment]
Aha, great point! What if we make a second table as a pointer to community drivers? If not, I think we should close this and keep that table for just “officially supported” drivers to reduce confusion.

**Comment by joscdk** [comment]
I have always been a big fan of a table of Community drivers :)

**Comment by tanner0101** [comment]
I think a second table for community drivers would be great. 👍

**Comment by Yasumoto** [comment]
Thanks, friends! Lemme know what y'all think 🎉

**Pull request merged**
