### PR TITLE
Module Testing

### PR DESCRIPTION
**Pull request by mcdappdev**
Added documentation about how to break the app up into multiple modules for in-line Xcode testing, and just overall better practice.

### CODE REVIEW

**Comment by mcdappdev** [comment]
I was also thinking about adding a new section about using MySQL with Travis/running tests on there. Any thoughts on that?

**Comment by mcdappdev** [comment]
👍  Thanks! I'll make whatever English changes necessary.

**Comment by BrettRToomey** [comment]
It's not really a big deal, it's just that we should pick one context to address the reader by and use it throughout the entire page :)

**Comment by mcdappdev** [comment]
Agreed! I'd love to hear input from Tanner and Logan too to see if they have a preference over which tense.

**Pull request merged**
