### PR TITLE
add Ubuntu 18.04 to the list of supported distros

### PR DESCRIPTION
**Pull request by dym-sh**

### CODE REVIEW

**Comment by joscdk** [comment]
@dym-sh thank you for this, if you already have the PR locally, would you mind adding `18.10` as well, then i will approve and merge :)

**Comment by dym-sh** [comment]
added 18.10 as well

**Comment by penny-coin** [comment]
Hey @dym-sh, you just merged a pull request, have a coin! 

You now have 1 coins.

**Comment by joscdk** [comment]
@tanner0101 can you deploy a new version of the docs when you have a minute :)

**Pull request merged**
