### PR TITLE
--branch=beta not needed anymore for new Vapor 3 projects

### PR DESCRIPTION
**Pull request by ksmandersen**

### CODE REVIEW

**Comment by vzsg** [comment]
That's not exactly true, neither is Vapor 3 tagged, nor is the api-template master updated. At this moment, you _do_ need the `--branch=beta` option.

But when it goes live, this PR will be useful :)

**Comment by tanner0101** [comment]
Once all of the API template's dependencies are non-RC, I will flip the switch. 👍

**Comment by bre7** [comment]
Hasn't this changed with the release of toolbox >= 3.1.6 ? Beta was removed along with the Swift 4.1 + Linux + Procfile fixes

**Comment by vzsg** [comment]
No, those sources were related to Vapor Cloud's beta version, unrelated to the current state of the api-template repo.

**Comment by twof** [comment]
Already fixed

**Pull request closed without merging**
